package model;

public enum CurrencyEnum {
    AED("Dirham dos Emirados Árabes Unidos"),
    AFN("Afegane Afegão"),
    ALL("Lek Albanês"),
    AMD("Dram Armênio"),
    ANG("Florim das Antilhas Holandesas"),
    AOA("Kwanza Angolano"),
    ARS("Peso Argentino"),
    AUD("Dólar Australiano"),
    AWG("Florim Arubano"),
    AZN("Manat Azerbaijano"),
    BAM("Marco Conversível da Bósnia e Herzegovina"),
    BBD("Dólar de Barbados"),
    BDT("Taka Bengali"),
    BGN("Lev Búlgaro"),
    BHD("Dinar Bareinita"),
    BIF("Franco Burundiano"),
    BMD("Dólar Bermudense"),
    BND("Dólar de Brunei"),
    BOB("Boliviano"),
    BRL("Real Brasileiro"),
    BSD("Dólar Bahamense"),
    BTN("Ngultrum Butanês"),
    BWP("Pula Botsuanesa"),
    BYN("Rublo Bielorrusso"),
    BZD("Dólar de Belize"),
    CAD("Dólar Canadense"),
    CDF("Franco Congolês"),
    CHF("Franco Suíço"),
    CLP("Peso Chileno"),
    CNY("Renminbi Chinês"),
    COP("Peso Colombiano"),
    CRC("Colón Costarriquenho"),
    CUP("Peso Cubano"),
    CVE("Escudo Cabo-Verdiano"),
    CZK("Coroa Tcheca"),
    DJF("Franco Djibutiano"),
    DKK("Coroa Dinamarquesa"),
    DOP("Peso Dominicano"),
    DZD("Dinar Argelino"),
    EGP("Libra Egípcia"),
    ERN("Nakfa Eritreia"),
    ETB("Birr Etíope"),
    EUR("Euro"),
    FJD("Dólar de Fiji"),
    FKP("Libra das Ilhas Malvinas"),
    FOK("Coroa Faroense"),
    GBP("Libra Esterlina"),
    GEL("Lari Georgiano"),
    GGP("Libra de Guernsey"),
    GHS("Cedi Ganês"),
    GIP("Libra de Gibraltar"),
    GMD("Dalasi Gambiano"),
    GNF("Franco Guineense"),
    GTQ("Quetzal Guatemalteco"),
    GYD("Dólar Guianense"),
    HKD("Dólar de Hong Kong"),
    HNL("Lempira Hondurenha"),
    HRK("Kuna Croata"),
    HTG("Gourde Haitiano"),
    HUF("Forint Húngaro"),
    IDR("Rupia Indonésia"),
    ILS("Novo Shekel Israelense"),
    IMP("Libra Manesa"),
    INR("Rupia Indiana"),
    IQD("Dinar Iraquiano"),
    IRR("Rial Iraniano"),
    ISK("Coroa Islandesa"),
    JEP("Libra de Jersey"),
    JMD("Dólar Jamaicano"),
    JOD("Dinar Jordaniano"),
    JPY("Iene Japonês"),
    KES("Xelim Queniano"),
    KGS("Som Quirguiz"),
    KHR("Riel Cambojano"),
    KID("Dólar de Kiribati"),
    KMF("Franco Comoriano"),
    KRW("Won Sul-Coreano"),
    KWD("Dinar Kuwaitiano"),
    KYD("Dólar das Ilhas Cayman"),
    KZT("Tenge Cazaque"),
    LAK("Kip Laosiano"),
    LBP("Libra Libanesa"),
    LKR("Rupia do Sri Lanka"),
    LRD("Dólar Liberiano"),
    LSL("Loti do Lesoto"),
    LYD("Dinar Líbio"),
    MAD("Dirham Marroquino"),
    MDL("Leu Moldavo"),
    MGA("Ariary Malgaxe"),
    MKD("Dinar Macedônio"),
    MMK("Kyat Birmanês"),
    MNT("Tögrög Mongol"),
    MOP("Pataca Macaense"),
    MRU("Ouguiya Mauritana"),
    MUR("Rupia Mauriciana"),
    MVR("Rufiyaa Maldívia"),
    MWK("Kwacha Malauiana"),
    MXN("Peso Mexicano"),
    MYR("Ringgit Malaio"),
    MZN("Metical Moçambicano"),
    NAD("Dólar Namibiano"),
    NGN("Naira Nigeriana"),
    NIO("Córdoba Nicaraguense"),
    NOK("Coroa Norueguesa"),
    NPR("Rupia Nepalesa"),
    NZD("Dólar Neozelandês"),
    OMR("Rial Omanense"),
    PAB("Balboa Panamenho"),
    PEN("Sol Peruano"),
    PGK("Kina Papua-Nova-Guineense"),
    PHP("Peso Filipino"),
    PKR("Rupia Paquistanesa"),
    PLN("Złoty Polonês"),
    PYG("Guarani Paraguaio"),
    QAR("Rial Catariano"),
    RON("Leu Romeno"),
    RSD("Dinar Sérvio"),
    RUB("Rublo Russo"),
    RWF("Franco Ruandês"),
    SAR("Rial Saudita"),
    SBD("Dólar das Ilhas Salomão"),
    SCR("Rupia Seichelense"),
    SDG("Libra Sudanesa"),
    SEK("Coroa Sueca"),
    SGD("Dólar de Singapura"),
    SHP("Libra de Santa Helena"),
    SLE("Leone de Serra Leoa"),
    SOS("Xelim Somali"),
    SRD("Dólar Surinamês"),
    SSP("Libra Sul-Sudanesa"),
    STN("Dobra de São Tomé e Príncipe"),
    SYP("Libra Síria"),
    SZL("Lilangeni de Essuatíni"),
    THB("Baht Tailandês"),
    TJS("Somoni Tadjique"),
    TMT("Manat Turcomeno"),
    TND("Dinar Tunisiano"),
    TOP("Paʻanga Tonganesa"),
    TRY("Lira Turca"),
    TTD("Dólar de Trinidad e Tobago"),
    TVD("Dólar Tuvaluano"),
    TWD("Novo Dólar Taiwanês"),
    TZS("Xelim Tanzaniano"),
    UAH("Hryvnia Ucraniana"),
    UGX("Xelim Ugandense"),
    USD("Dólar Americano"),
    UYU("Peso Uruguaio"),
    UZS("Som Uzbeque"),
    VES("Bolívar Soberano Venezuelano"),
    VND("Dong Vietnamita"),
    VUV("Vatu de Vanuatu"),
    WST("Tālā Samoano"),
    XAF("Franco CFA Central"),
    XCD("Dólar do Caribe Oriental"),
    XDR("Direitos Especiais de Saque"),
    XOF("Franco CFA Ocidental"),
    XPF("Franco CFP"),
    YER("Rial Iemenita"),
    ZAR("Rand Sul-Africano"),
    ZMW("Kwacha Zambiano"),
    ZWL("Dólar Zimbabuense");

    public final String currencyName;

    CurrencyEnum(String currencyName) {
        this.currencyName = currencyName;
    }

    public static CurrencyEnum validateEnum(String currency) {
        for (CurrencyEnum currencyEnum : CurrencyEnum.values()) {
            if (currencyEnum.name().equals(currency)) {
                return CurrencyEnum.valueOf(currency);
            }
        }
        return null;
    }
}
